name: phillips_hue
description: A small library with utility classes for communicating with
  Phillips Hue bulbs.
version: 0.0.1
author: Kim Rostgaard Christensen <krc@retrospekt.dk>
homepage: http://retrospekt.dk

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
